### PR TITLE
Allow search customer feature via API

### PR DESCRIPTION
**Pull request by lucasgomide**
issue #32

### CODE REVIEW

**Comment by lucasgomide** [comment]
@joelibaceta and @hcasatti Can you guys review this PR ? 

When #34 was merged I'll solve some conflicts.

**Comment by lucasgomide** [comment]
@joelibaceta  @hcasatti can you guys review it ?

**Comment by lucasgomide** [comment]
@victorgodinho-meli  Why did you closed it? It took almost 3 years to be touched by one of you guys. Could you provide any reason to close that?

**Comment by victorgodinho-meli** [comment]
Hi Lucas! First of all thank you for your help and time in send us a PR with corrections and improvements in our SDK that was not having the necessary attention from us. We are doing a lot of internal changes to do not abandon again our SDKs and give the proper attention. On this way, we are close to launch our 2.0.0 which will correct not only this point as some others. We took in our radar urs recommendations here, as well as others we had, to develop our 2.0.0 that will be productive in March.

Thank u again, I hope u enjoy the v2, and having any improvement, such comment will be very valuable and we would love have a new start from now!

See u! Peace!

**Pull request closed without merging**
