### PR TITLE
Fix test suit

### PR DESCRIPTION
**Pull request by lucasgomide**
Issue reference https://github.com/mercadopago/sdk-ruby/issues/33

### CODE REVIEW

**Comment by lucasgomide** [comment]
@joelibaceta, @hcasatti  Can you guys review this PR ? 

I've added travis CI on this commit  [4c98054](
https://github.com/mercadopago/sdk-ruby/pull/34/commits/4c980542fe9e02db0d4620817f84ccc06179d620)

Let me know if you agree to use Travis.org as CI. If so, I will need change the status image to set your repo. Currently I've set up base on my fork. I'll change it after u set up this repo on MercadoPago Travis account.

**Comment by joelibaceta** [comment]
@lucasgomide thanks for the contribution I'll gonna check this

**Comment by lucasgomide** [comment]
Tks @joelibaceta. I'm waiting for your code review  (;

**Comment by lucasgomide** [comment]
@joelibaceta  @hcasatti can you guys review it ?

**Comment by lucasgomide** [comment]
@victorgodinho-meli Why did you closed it? It took 3 years to be touched by one of you guys. 
Could you provide any reason to close that?

**Pull request closed without merging**
